src/HTA/HTA.Website.MVC.Example/Controllers/AdventureLocationController.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using HTA.Adventures.API.ServiceInterface;
using HTA.Adventures.BusinessLogic;
using HTA.Adventures.Models;
using HTA.Adventures.Models.Types;
using HTA.Website.MVC.Example.API;
using HTA.Website.MVC.Example.Models;

namespace HTA.Website.MVC.Example.Controllers
{
    public class AdventureLocationController : Controller
    {
        private readonly IAdventureLocationRepository _adventureLocationRepository = new APIAdventureLocationProxy();
        private readonly IAdventureRegionRepository _adventureRegionRepository = new APIAdventureRegionProxy();
        public ActionResult Index()
        {
            IList<AdventureLocation> locations = new List<AdventureLocation>();
            //locations = _adventureLocationRepository.GetAdventureLocations();
            return View(locations);
        }

        public ActionResult Create()
        {
            var model = new AdventureLocationModel();

            //model.SelectableAdventureRegions = _adventureRegionRepository.GetAdventureRegions();
            //model.SelectableAdventureRegions.Insert(0, Region.CreateNewRegion);
            //model.SelectableAdventureRegions.Insert(0, new AdventureRegion(new LocationPoint() { Lat = double.MaxValue }, "** Create New Region **", "", ""));
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(AdventureLocationModel model)
        {
            using (var businessValidator = new LocationBusiness())
            {
                IList<ValidationResult> validationErrorResults = new List<ValidationResult>();
                if (businessValidator.Validate(model.AdventureLocation, validationErrorResults))
                {
                    // Assign the adventure region to the location object.
                    model.AdventureLocation
                        .Region = _adventureRegionRepository
                            .GetAdventureRegion(model.AdventureLocation.Region.Id);

                    var locationResponse = _adventureLocationRepository.SaveAdventureLocation(model.AdventureLocation);

                    return View("Details", locationResponse);
                }

                ErrorUtility.TransformResponseErrors(ModelState, validationErrorResults);

                model.SelectableAdventureRegions = _adventureRegionRepository.GetAdventureRegions();
                model.SelectableAdventureRegions.Insert(0, Region.CreateNewRegion);

            }


            return View(model);
        }

        public ActionResult Details(string id)
        {
            var location = _adventureLocationRepository.GetAdventureLocation(id);
            return View(location);
        }

        public ActionResult Edit(string id)
        {
            var locationResponse = _adventureLocationRepository.GetAdventureLocation(id);

            var model = new AdventureLocationModel()
                            {
                                AdventureLocation = locationResponse,
                                SelectableAdventureRegions = _adventureRegionRepository.GetAdventureRegions()
                            };
            model.SelectableAdventureRegions.Insert(0, Region.CreateNewRegion);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(AdventureLocationModel model)
        {
            using (var businessValidator = new LocationBusiness())
            {
                IList<ValidationResult> validationErrorResults = new List<ValidationResult>();
                if (businessValidator.Validate(model.AdventureLocation, validationErrorResults))
                {
                    // Assign the adventure region to the location object.
                    model.AdventureLocation
                        .Region = _adventureRegionRepository
                                            .GetAdventureRegion(model.AdventureLocation.Region.Id);

                    var location = _adventureLocationRepository.SaveAdventureLocation(model.AdventureLocation);
                    return RedirectToAction("Details", location);
                }

                model.SelectableAdventureRegions = _adventureRegionRepository.GetAdventureRegions();
                model.SelectableAdventureRegions.Insert(0, Region.CreateNewRegion);

                ErrorUtility.TransformResponseErrors(ModelState, validationErrorResults);

                return View(model);
            }
        }

        public ActionResult Delete(string id)
        {
            throw new System.NotImplementedException();
        }
    }
}

src/HTA/HTA.Website.MVC.Example/Controllers/AdventureRegionController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using HTA.Adventures.Models;
using HTA.Adventures.Models.Types;
using HTA.Website.MVC.Example.API;
using HTA.Website.MVC.Example.Models;

namespace HTA.Website.MVC.Example.Controllers
{
    public class AdventureRegionController : Controller
    {
        private readonly IAdventureRegionRepository _adventureRegionRepository = new APIAdventureRegionProxy();
        private readonly IAdventureLocationRepository _adventureLocationRepository = new APIAdventureLocationProxy();

        public ActionResult Index()
        {
            var regions = _adventureRegionRepository.GetAdventureRegions();

            return View(regions);
        }

        public ActionResult Details(string id)
        {
            var region = _adventureRegionRepository.GetAdventureRegion(id);
            var regionLocations = _adventureLocationRepository.GetRegionAdventureLocations(id);

            var model = new AdventureRegionAdventureLocationsModel();
            model.Region = region;
            model.Locations = regionLocations;

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Region model)
        {
            if (ModelState.IsValid)
            {
                model = _adventureRegionRepository.SaveAdventureRegion(model);

                var item = new AdventureRegionAdventureLocationsModel() { Region = model, Locations = new List<AdventureLocation>() };
                return View("Details", item);
            }
            return View(model);
        }

        public ActionResult Locations(string id)
        {
            var region = _adventureRegionRepository.GetAdventureRegion(id);
            var regionLocations = _adventureLocationRepository.GetRegionAdventureLocations(id);

            var model = new AdventureRegionAdventureLocationsModel();
            model.Region = region;
            model.Locations = regionLocations;

            return View(model);
        }

        public ActionResult Edit(string id)
        {
            var region = _adventureRegionRepository.GetAdventureRegion(id);
            var regionLocations = _adventureLocationRepository.GetRegionAdventureLocations(id);

            var model = new AdventureRegionAdventureLocationsModel();
            model.Region = region;
            model.SelectedLocations = regionLocations.Select(s => s.Id).ToList();
            model.Locations = _adventureLocationRepository.GetAdventureLocations();
            // i dont think we need to add one, just do it by default.
            //model.Locations.Insert(0, new AdventureLocation(new LocationPoint() { Lat = double.MaxValue, Lon = double.MaxValue }, "Create New", string.Empty, string.Empty));

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(AdventureRegionAdventureLocationsModel model)
        {
            if (ModelState.IsValid)
            {
                var locations = new List<AdventureLocation>();
                foreach (var locationId in model.SelectedLocations)
                {
                    // Get existing location object
                    var locationResponse = _adventureLocationRepository.GetAdventureLocation(locationId);

                    // set location.region to new region
                    locationResponse.Region = model.Region;

                    // save in API and get response
                    var saveResponse = _adventureLocationRepository.SaveAdventureLocation(locationResponse);

                    // add response to this response.locations
                    locations.Add(saveResponse);
                }

                var region = model.Region;

                model.Region = _adventureRegionRepository.SaveAdventureRegion(region);
                model.Locations = locations;
                return View("Details", model);
            }

            model.Locations = _adventureLocationRepository.GetAdventureLocations();
            return View(model);
        }
    }
}

src/HTA/HTA.Website.MVC.Example/Views/AdventureLocation/Create.cshtml
@model HTA.Website.MVC.Example.Models.AdventureLocationModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Create</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/chosen.jquery.js")" type="text/javascript"></script>
<link href="/Content/chosen.css" rel="stylesheet" type="text/css" />
@using (Html.BeginForm())
{
    @Html.ValidationSummary(false)
    <fieldset>
        <legend>AdventureLocation</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdventureLocation.Name)
            @Html.ValidationMessageFor(model => model.AdventureLocation.Name)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdventureLocation.Address)
            @Html.ValidationMessageFor(model => model.AdventureLocation.Address)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Picture)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdventureLocation.Picture)
            @Html.ValidationMessageFor(model => model.AdventureLocation.Picture)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Point.Lat)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdventureLocation.Point.Lat)
            @Html.ValidationMessageFor(model => model.AdventureLocation.Point.Lat)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Point.Lon)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdventureLocation.Point.Lon)
            @Html.ValidationMessageFor(model => model.AdventureLocation.Point.Lon)
        </div>
@*        <div>
            @Html.DropDownListFor(m => m.AdventureLocation.Region.Id, Model.SelectableAdventureRegions.Select(s => new SelectListItem { Text = s.Name, Value = s.Id }), new { id = "selectAdventureRegion", Class = "chzn-select" })
        </div>*@
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">
    $(".chzn-select").chosen();

    //        $(".chzn-select-deselect").chosen({ allow_single_deselect: true });
</script>

src/HTA/HTA.Website.MVC.Example/Views/AdventureLocation/Details.cshtml
@model HTA.Adventures.Models.Types.AdventureLocation
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Details</h2>
<fieldset>
    <legend>AdventureLocation</legend>
    <div class="display-label">
        Name : @Html.DisplayFor(model => model.Name)
    </div>
    <div class="display-label">
        Address : @Html.DisplayFor(model => model.Address)
    </div>
    <div class="display-label">
        Picture : @Html.DisplayFor(model => model.Picture)
    </div>
    <div class="display-label">
        Lat : @Html.DisplayFor(model => model.Point.Lat)
    </div>
    <div class="display-label">
        Lon : @Html.DisplayFor(model => model.Point.Lon)
    </div>
    <div class="display-label">
        Adventure Region : @Html.DisplayFor(model => model.Region.Name) [<i>@Html.DisplayFor(model => model.Region.Id)</i>]
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/HTA/HTA.Website.MVC.Example/Views/AdventureLocation/Edit.cshtml
@model HTA.Website.MVC.Example.Models.AdventureLocationModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Edit</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/chosen.jquery.js")" type="text/javascript"></script>
<link href="/Content/chosen.css" rel="stylesheet" type="text/css" />
@using (Html.BeginForm())
{
    @Html.ValidationSummary(false)
    <fieldset>
        <legend>AdventureLocationModel</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdventureLocation.Name)
            @Html.ValidationMessageFor(model => model.AdventureLocation.Name)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdventureLocation.Address)
            @Html.ValidationMessageFor(model => model.AdventureLocation.Address)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Picture)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdventureLocation.Picture)
            @Html.ValidationMessageFor(model => model.AdventureLocation.Picture)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Point.Lat)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdventureLocation.Point.Lat)
            @Html.ValidationMessageFor(model => model.AdventureLocation.Point.Lat)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Point.Lon)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AdventureLocation.Point.Lon)
            @Html.ValidationMessageFor(model => model.AdventureLocation.Point.Lon)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.AdventureLocation.Region)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m => m.AdventureLocation.Region.Id, Model.SelectableAdventureRegions.Select(s => new SelectListItem { Text = s.Name, Value = s.Id }), new { id = "selectAdventureRegion", Class = "chzn-select" })
        </div>
        <p>
            @Html.HiddenFor(model => model.AdventureLocation.Id)
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">
    $(".chzn-select").chosen();

    //        $(".chzn-select-deselect").chosen({ allow_single_deselect: true });
</script>

src/HTA/HTA.Website.MVC.Example/Views/AdventureLocation/Index.cshtml
@model IEnumerable<HTA.Adventures.Models.Types.AdventureLocation>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Name
        </th>
        <th>
            Address
        </th>
        <th>
            Picture
        </th>
        <th>
            Lat,Lon
        </th>
        <th>
            Region
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Picture)
            </td>
            <td>@Html.DisplayFor(model => item.Point.LatLon)
            </td>
            <td>
                @if (!string.IsNullOrEmpty(item.Region.Name))
                { 
                    @Html.ActionLink(item.Region.Name, "Details", "AdventureRegion", new { item.Region.Id }, new { });
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>